import pygame as pg
import json

hey = 'Hey'

file = open("HatHome song\\save_file.txt", "r")
data_json = json.load(file)


WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (160, 160, 160)
GREY = (126, 126, 126)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
LIGHTBLUE = (0, 255, 255)
BLUE = (0, 35, 255)
PURPLE = (208, 0, 255)

# Game Settings
RESOLUTION = [[2560, 1440], [1920, 1080], [1680, 1050], [1440, 900], [1366, 768], [1280, 800], [768, 1024]]
WIDTH = data_json['settings']['resolution'][0]
HEIGHT = data_json['settings']['resolution'][1]
PATCHW = WIDTH/1600
PATCHH = HEIGHT/900
DIAGONAL = HEIGHT / WIDTH
FPS = 60
TITLE = "HatHome"
BGCOLOR = BLACK
TILESIZE = 50 * PATCHW
GRIDWIDTH = WIDTH / TILESIZE
GRIDHEIGHT = HEIGHT / TILESIZE
STATUSWIND = False

#Sound
VOLUME = data_json['volumes']['general']
VOLUMESOUNDS = data_json['volumes']['sound']
VOLUMEMUSIC = data_json['volumes']['music']


#MENU
IMG_PLAY = '\Play.png'
XPLAY = 100*PATCHW
YPLAY = 100*PATCHH
XOPTION = 100*PATCHW
YOPTION = 200*PATCHH
XSAUVEGARDE = 100*PATCHW
YSAUVEGARDE = 300 * PATCHH

XBACK = 100*PATCHW
YBACK = 800*PATCHH
XCONFIRM = 200*PATCHW
YCONFIRM = 800*PATCHH
XVOLUME = 525*PATCHW
YVOLUME = 100*PATCHH
XPVOLUME = 610*PATCHW
YPVOLUME = 100*PATCHH
XMVOLUME = 470*PATCHW
YMVOLUME = 100*PATCHH
XTVOLUME = 100*PATCHW
YTVOLUME = 100*PATCHH

XSOUNDSVOLUME = 525*PATCHW
YSOUNDSVOLUME = 200*PATCHH
XPSOUNDSVOLUME = 610*PATCHW
YPSOUNDSVOLUME = 200*PATCHH
XMSOUNDSVOLUME = 470*PATCHW
YMSOUNDSVOLUME = 200*PATCHH
XTSOUNDSVOLUME = 100*PATCHW
YTSOUNDSVOLUME = 200*PATCHH

XMUSICVOLUME = 525*PATCHW
YMUSICVOLUME = 300*PATCHH
XPMUSICVOLUME = 610*PATCHW
YPMUSICVOLUME = 300*PATCHH
XMMUSICVOLUME = 470*PATCHW
YMMUSICVOLUME = 300*PATCHH
XTMUSICVOLUME = 100*PATCHW
YTMUSICVOLUME = 300*PATCHH

XRESOLUTION = 100*PATCHW
YRESOLUTION = 400*PATCHH

IMG_QUIT = '\Quit.png'
XQUIT = 1500*PATCHW
YQUIT = 50*PATCHH

#MINIMAP
MWIDTH = 150*PATCHW
MHEIGHT = MWIDTH


#Blocks
WALL_IMG = '\Wall.png'
WALL_INV_IMG = '\Wall_inventory.png'
WALL_LIFE_IMAGE = '\Wall_life.png'
WALL_LIFE_IMAGE_EMPTY = '\Wall_life_empty.png'
VEGETATION_IMG = '\Vegetation2.png'
GROUND_IMG = '\Ground.png'

MUSIC = '\\farm.mp3'
CONSTRUCT_SOUND = '\\buildmur.wav'
UNCONSTRUCT_SOUND = '\\unbuildmur.wav'
BUILD_SOUND1 = '\\posermur.wav'
BUILD_SOUND2 = '\\posermur2.wav'
BUILD_SOUND3 = '\\posermur3.wav'
DESTRUCT_SOUND1 = '\\cassermur1.wav'
DESTRUCT_SOUND2 = '\\cassermur2.wav'
BUY_SOUND = '\\achat.wav'
#DESTRUCT_SOUND3 = '\\cassermur3.wav' son pas ouf mais on peut peutetre s'en servir

# Ship
SHIP_X = 5000/2*PATCHW
SHIP_Y = 5000/2*PATCHH
SHIP_MAX_LIFE = 1000
SHIP_LIFE = 1000
SHIP_IMAGE = '\Ship.png'
SHIP_IMAGE_EMPTY = '\Ship_empty.png'
SHIP_IMAGE_BUTTON_WAVE = '\Spritebutton_wave.png'

#Balise
SONAR_IMAGE = '\\Sonar.png'
SONAR_X = 2200*PATCHW
SONAR_Y = 2400*PATCHH
SONARTEXT_X = 30*PATCHW
SONARTEXT_Y = 850*PATCHH

# Player
PLAYER_X = 2800*PATCHW
PLAYER_Y = 2500*PATCHH
PLAYER_SPEED = 240*PATCHW
PLAYER_BANK_IMG = '\SpritePlayer.png'
PLAYER_CONSTRUCT_BANK_IMG = '\SpritePlayer_construct.png'
PLAYER_COIN_BANK_IMG = '\SpritePlayer_coin.png'
PLAYER_COIN_EMPTY_BANK_IMG = '\SpritePlayer_coin_empty.png'
PLAYER_HIT_RECT = pg.Rect(0, 0, 78, 96)
INVINCIBILITY_TIME = 50
WALK1 = '\pas1.wav'
WALK2 = '\pas2.wav'
WALK3 = '\pas3.wav'
WALK4 = '\pas4.wav'
WALK5 = '\pas5.wav'
WALK6 = '\pas6.wav'
WALK7 = '\pas7.wav'

DAMAGE_SOUND1 = '\\degats1.wav'
DAMAGE_SOUND2 = '\\degats2.wav'
DAMAGE_SOUND3 = '\\degats3.wav'

HUD_BAR_IMG = '\\Hud_Bar.png'

CONSTRUCT_DISTANCE = 200*PATCHW

# Coins
COINS_START = data_json['inventory']['coins']
COINS_IMAGE = '\Coins.png'
GEMSTONE_IMAGE = '\Gemstone.png'
# Wall
WALL_START = data_json['inventory']['walls']

#LIFE
PLAYER_LIFE = '\Life.png'
PLAYER_LIFE_EMPTY = '\Life_empty.png'
PLAYER_LIFE_STAT = data_json['player']['life']
LIFE_X = 10 *PATCHW
LIFE_Y = 10 *PATCHH

#STAMINA
PLAYER_STAMINA = '\Stamina.png'
PLAYER_STAMINA_EMPTY = '\Stamina_empty.png'
PLAYER_STAMINA_STAT = 50
PLAYER_STAMINA_REDUCE = 0.65
PLAYER_STAMINA_REGEN = 0.10
PLAYER_STAMINA_EFFECT = 2
STAMINA_X = 300 *PATCHW
STAMINA_Y = 10 *PATCHH
EXPERIENCE_X = 590 *PATCHW
EXPERIENCE_Y = 10 *PATCHH


# Mob
GLOBU_IMG = '\GlobuzarSprite.png'
GLOBU_IMG_DIE = '\GlobuzarSprite_die.png'
GLOBU_IMG_ANGRY = '\GlobuzarSpriteAngry.png'
GLOBU_SPEED = 350*PATCHW
GLOBU_HIT_RECT = pg.Rect(0, 0, 52, 100)
GLOBU_DROPCHEST = 0.01 #(4+1 chance / 100 car le 0 compt)
GLOBU_RANGE_B_PLAYER = 20
GLOBU_LIFE = 100
GLOBU_LIFE_IMAGE = '\Globu_life.png'
GLOBU_LIFE_IMAGE_EMPTY = '\Globu_life_empty.png'
COINS_DROP_MAX = 5
COINS_DROP_MIN = 1
EXPERIENCE_DROP_MIN = 1
EXPERIENCE_DROP_MAX = 3
GLOBUZAR_DAMAGE = 20
GLOBUZAR_WALL_ATTACK = 1
GLOBUZAR_AWARE = 500*PATCHW

#Dealer
DEALER_X = 2800 * PATCHW
DEALER_Y = 2500 * PATCHH
HURTICA_X = 2950 * PATCHW
HURTICA_Y = 2500 * PATCHH
DEALER_IMG = '\SpriteDealer.png'
HURTICA_IMG = '\SpriteHurtica.png'

#Chest
CHEST_IMAGE = '\Chest.png'

# Map
MAP = 'map.txt'
MAP_IMAGE = '\Map.png'

#MASTER MIND
CLOCK_X = 1500*PATCHW
CLOCK_Y = 210*PATCHH

# Inventory
IMG_INVENTORY = '\inventory.png'
MAXIMUM_TIME_TOGGLETIMER = 15
INVENTORY_DEALER_X = 990*PATCHW
INVENTORY_DEALER_Y = 200*PATCHH
INVENTORYX = 160*PATCHW
INVENTORYY = 200*PATCHH
SUBX = 70*PATCHW
SUBY = 50*PATCHH
SPACE_INV_X = 128 * PATCHW
SPACE_INV_Y =  90 * PATCHH
NUMBERS_IMAGE = '/Numbers.png'
LETTERS_IMAGE = '/Letters.png'
MENU_IMG = '/Inventory_menu.png'
TELEPORTHAT_IMAGE = '/Teleport_hat.png'
BUTTON_PRIMARY_IMAGE = '/Button_Primary.png'
BUTTON_SECONDARY_IMAGE = '/Button_Secondary.png'
BUTTON_HAT_IMAGE = '/Button_Hat.png'

DISTANCE_NUMBER = 3*PATCHW
BUTTON_SPACE_CLICK = 40
XWAVELAUNCH = INVENTORYX+250*PATCHW
YWAVELAUNCH = INVENTORYY+380*PATCHH
IS_COINS = 63*PATCHW
IS_LVL = 163*PATCHW
IS_WALL = 263*PATCHW
IS_STATS = 50*PATCHH

WAVEACUPDATE = data_json['wave']['selectwave']

INVENTORY_DEALER_PRIMARY_X = 58*PATCHW
INVENTORY_DEALER_PRIMARY_Y = 67*PATCHH
ECART_PX = 72*PATCHW
ECART_PY = 63*PATCHH
ECART_SX = 48*PATCHW
ECART_HX = 44*PATCHW


PRIMINVSLOTS = data_json['inventory']['priminvslots']
SECONDINVSLOTS = data_json['inventory']['secondinvslots']
HATINVSLOTS = data_json['inventory']['hatinvslots']

SELLINGITEMPRIMARY = data_json['inventory']['sellingitemprimary']
PRICEITEMPRIMARY = data_json['inventory']['priceitemprimary']
SELLINGITEMSECONDARY = data_json['inventory']['sellingitemsecondary']
PRICEITEMSECONDARY = data_json['inventory']['priceitemsecondary']
SELLINGITEMHAT = data_json['inventory']['sellingitemhat']
PRICEITEMHAT = data_json['inventory']['priceitemhat']

'''
SLOT2EQ = "Gold45"
SLOT1EQ = "Wavax"
SLOT3EQ = "Aspirator"
SLOT4EQ = "Teleport_Hat"

PRIMINVSLOTS = [SLOT1EQ, SLOT2EQ, None, None, None]
SECONDINVSLOTS = [SLOT3EQ, None, None]
HATINVSLOTS = [SLOT4EQ, None, None, None]

SELLINGITEMPRIMARY = ['Wavax', 'Gold45', 'Wavax', 'Gold45', 'Wavax', 'Gold45', None, None, None, None, None, None, None, None, None]
PRICEITEMPRIMARY = [20, 30, 20, 30, 20, 30, None, None, None, None, None, None, None, None, None]
SELLINGITEMSECONDARY = ['Aspirator', 'Aspirator', 'Aspirator', 'Aspirator', None, None]
PRICEITEMSECONDARY = [100, 100, 100, 100, None, None]
SELLINGITEMHAT = ['Teleport_Hat', 'Teleport_Hat', 'Teleport_Hat', 'Teleport_Hat', None, None, None, None]
PRICEITEMHAT = [100, 100, 100, 100, None, None, None, None]
'''



IS_IMAGE_SLOT1_X = 216*PATCHW
IS_IMAGE_SLOT1_Y = 231*PATCHH

XSLOT1_BUTTON = INVENTORYX+213*PATCHW
YSLOT1_BUTTON = INVENTORYY+229*PATCHH
XSLOT2_BUTTON = INVENTORYX+315*PATCHW
YSLOT2_BUTTON = INVENTORYY+229*PATCHH
XSLOT3_BUTTON = INVENTORYX+339*PATCHW
YSLOT3_BUTTON = INVENTORYY+164*PATCHH
XSLOT4_BUTTON = INVENTORYX+278*PATCHW
YSLOT4_BUTTON = INVENTORYY+149*PATCHH

IS_IMAGE_SLOT2_X = 319*PATCHW
IS_IMAGE_SLOT2_Y = 232*PATCHH
IS_IMAGE_SLOT3_X = 343*PATCHW
IS_IMAGE_SLOT3_Y = 166*PATCHH
IS_IMAGE_SLOT4_X = 279*PATCHW
IS_IMAGE_SLOT4_Y = 152*PATCHH

INVENTORY_PLAYER_PRIMARY_X = 55*PATCHW
INVENTORY_PLAYER_PRIMARY_Y = 326*PATCHH
INVENTORY_PLAYER_SECONDARY_X = 295*PATCHW
INVENTORY_PLAYER_SECONDARY_Y = 319*PATCHH
INVENTORY_PLAYER_HAT_X = 53*PATCHW
INVENTORY_PLAYER_HAT_Y = 381*PATCHH


#WEAPONS
# [Weapons]
CD_SELECT_GUN = 20
#Gold45
GOLD45_IMAGE = '\Gold45.png'
GOLD45_BULLET_IMAGE = '\Gold45_bullet.png'
GOLD45_BULLET_FIRESOUND = '\Gold45_shot.wav'

ASPIRATOR_IMAGE = '\Aspirator.png'
ASPIRATOR_IMAGE_BACK = '\Aspirator_Back.png'
ASPIRATOR_SPEED = 800*PATCHW
ASPIRATOR_RANGE = 800*PATCHW
#Wavax
WAVAX_IMAGE = '\Wavax.png'
WAVAX_BULLET_IMAGE = '\Wavax_bullet.png'

WAVAX_BULLET_FIRESOUND = '\Gold45_shot.wav'

file.close()
